version: '3'
services:
  browser:
    # See inside via VNC with the "debug" version
    image: selenium/standalone-chrome-debug
    
    # Slightly faster headless version
    #image: selenium/standalone-chrome    

    network_mode: "host"
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access

  ruby:
    build: .
    image: "richdownie/fsar_samples"
    volumes:
      - .:/app
    depends_on: 
      - browser
